# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HWapp', '0002_auto_20170830_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwapp',
            name='koufen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hwapp',
            name='qq',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='hwapp',
            name='xingbie',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1, max_length=1),
        ),
    ]
