# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HWapp', '0007_auto_20170902_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwapp',
            name='shengri',
            field=models.DateField(null=True),
        ),
    ]
