# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HWapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwapp',
            name='banji',
            field=models.CharField(default='C0000', max_length=8),
        ),
        migrations.AddField(
            model_name='hwapp',
            name='chuangpu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hwapp',
            name='dianhua',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hwapp',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='hwapp',
            name='jiaoshi',
            field=models.CharField(default='\u4e00\u6559000', max_length=8),
        ),
        migrations.AddField(
            model_name='hwapp',
            name='qingshi',
            field=models.CharField(default='0#000', max_length=20),
        ),
        migrations.AddField(
            model_name='hwapp',
            name='qq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hwapp',
            name='xingbie',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1),
        ),
    ]
