# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HWapp', '0003_auto_20170830_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwapp',
            name='qq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hwapp',
            name='xingbie',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1),
        ),
    ]
