# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HWapp', '0004_auto_20170830_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='hwapp',
            name='zhengzhimianmao',
            field=models.IntegerField(choices=[(1, '\u56e2\u5458'), (2, '\u515a\u5458'), (3, '\u5176\u4ed6')], default=3),
        ),
        migrations.AlterField(
            model_name='hwapp',
            name='qingshi',
            field=models.CharField(default='\u75370#000', max_length=20),
        ),
        migrations.AlterField(
            model_name='hwapp',
            name='xingbie',
            field=models.IntegerField(choices=[(1, '\u7537'), (2, '\u5973')], default=1),
        ),
    ]
