# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HWapp', '0005_auto_20170831_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hwapp',
            name='jiaoshi',
        ),
        migrations.AddField(
            model_name='hwapp',
            name='banjizhiwu',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hwapp',
            name='tongbao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hwapp',
            name='xueshenghuizhiwu',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hwapp',
            name='zhengzhimianmao',
            field=models.IntegerField(choices=[(1, '\u5171\u9752\u56e2\u5458'), (2, '\u515a\u5458'), (3, '\u5176\u4ed6')], default=3),
        ),
    ]
